services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    tty: true
    stdin_open: true
    ports:
      - '1987:1987'
      - '5173:5173'
      - '8000:8000'
    depends_on:
      - db
    networks: [app_net]
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks: [app_net]

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks: [app_net]

volumes:
  pgdata:

networks:
  app_net:
